### ISSUE TITLE
Adding multiple members with SADD

### ISSUE THREAD

**Issue by dchancogne** [M6Web/RedisMock#33]
Any particular reason you do not support adding multiple members with SADD? Or just didn't get to it yet?

**Comment by mikaelrandy** [comment]
This issue is no more relevant, as SADD handle multiple members adding
https://github.com/M6Web/RedisMock/blob/master/src/M6Web/Component/RedisMock/RedisMock.php#L237

**Comment by dchancogne** [comment]
This is great. Thank you @mikaelrandy !
