### ISSUE TITLE
ZADD: allowing multiple member-score pairs

### ISSUE THREAD

**Issue by nleroy** [M6Web/RedisMock#40]
Hi

Right now I'm using Predis as redis library. The ZADD function is defined this way:
zadd($key, array $membersAndScoresDictionary)

When using RedisMock in my unit tests, I get an error stating that argument 3 is missing for zadd. (as ZADD is defined as zadd($key, $score, $member)).

Does it seem logical to add this change? Or do other PHP Redis library implment zadd differently?

**Comment by nleroy** [comment]
By the way: I see SADD already allows multiple members.

**Comment by nleroy** [comment]
I'm sorry, apparently it is possible to use zadd the same way in Predis as defined in RedisMock. I changed my code and it works.

**Comment by omansour** [comment]
no problem that's for the best :) 

don't hesitate to report any problem in the future.

**Comment by nleroy** [comment]
Thanks!
