### ISSUE TITLE
Mock several servers

### ISSUE THREAD

**Issue by zzgab** [M6Web/RedisMock#52]
Currently the client mocks a connection to one single Redis server, and storage is static, shared across all instances of the mock (which is good).
I would like to use a test scenario involving two (or more) Redis servers. The storage should remain mock-static, but per "Redis server".

Shall I fork and propose?

**Comment by zzgab** [comment]
@fdubost @omansour Up ?

**Comment by omansour** [comment]
yes sure. would be nice to read you.
