### ISSUE TITLE
Wrong signature for zadd

### ISSUE THREAD

**Issue by magnetik** [M6Web/RedisMock#73]
Predis ClientInterface declares zadd as: 

https://github.com/nrk/predis/blob/111d100ee389d624036b46b35ed0c9ac59c71313/src/ClientInterface.php#L116
` * @method int    zadd($key, array $membersAndScoresDictionary)`

While RedisMock declares:
https://github.com/M6Web/RedisMock/blob/f4c6f55497becb1c6f5d9593b2a74163e0281858/src/M6Web/Component/RedisMock/RedisMock.php#L931
` public function zadd($key, $score, $member) {`

Am I missing something?

**Comment by Meroje** [comment]
[Redis 2.4](https://redis.io/commands/zadd#history) added the possibility to add multiple elements with a single call, this signature targets an earlier version. There may be other outdated signatures in there.

**Comment by magnetik** [comment]
I was sort of okay with the limitation of having one element by call, but the difference in signature makes it impossible to use the mock as a Predis client replacement, right? 

I'll try to do a PR.

**Comment by magnetik** [comment]
@Meroje Can you take a look at the PR linked above (#80)?
