### ISSUE TITLE
Redis command `eval` is not supported by RedisMock.

### ISSUE THREAD

**Issue by sevrugin** [M6Web/RedisMock#75]
Hello!

I work with the Laravel framework and start switching to the latest version (5.8)
I use the `josiasmontag / laravel-redis-mock` library (which uses your library) to test Laravel queues
Starting with version 5.8, Laravel Redis starts using the function `eval`, and I get this error

Is it possible to add the `eval` function to the RedisMock class?

I will be very grateful for this!

**Comment by omansour** [comment]
Hello. 

Thanks for the notes. Feel free to add a pull request implementing the command. However, I think this will be almost impossible as we will need a lua interpreter !

**Comment by sevrugin** [comment]
Done. Could you have a look please?
https://github.com/M6Web/RedisMock/pull/76

**Comment by sevrugin** [comment]
@omansour ^^

**Comment by omansour** [comment]
done

**Comment by jdavidbakr** [comment]
Hey @sevrugin - in my case I'm using Laravel's Redis::funnel() which requires eval() to return a non-null value.  Would it break your implementation if this was changed to return true instead of returning null?

**Comment by jdavidbakr** [comment]
I just sent a pull request that returns true for both of those functions.
